title = "Yash Savani"
baseURL = "https://yashsavani.com"
languageCode = "en-us"
enableEmoji = true
math = true
googleAnalytics = "G-P1NJDJ6RHK"

[params]
    author = "Yash Savani"
    description = "Academic website for Yash Savani."
    favicon = "favicon.ico"
    logo = ""

[permalinks]
"/" = "/:filename"

[markup.goldmark.renderer]
    unsafe = true  # allow raw HTML in markdown files


